import obj from './first';
import {CXM} from './first';
console.log(obj[0].fn);
console.log(obj[1].empId);
console.log(new CXM.SDA.Person('Tom','Riley').firstName);
import {label} from './first';
console.log(label);
console.log(obj[2]);
import {XX} from './first';
console.log(XX.surname);
import {add} from './first';
console.log(add(2,3,5));
console.log(obj[3].surname);
console.log(obj[4](3,3,3));
console.log(new obj[5].SDA.Person('Nicholas','Cage').firstName);
import {dabbu} from './first';
console.log(dabbu);